### ISSUE TITLE
Problème avec les zones sans programme associé

### ISSUE THREAD

**Issue by mezzarobba** [trahay/remora_programmer#1]
Bonjour,

Le chargement de la page d'accueil échoue avec l'erreur ci-dessous si l'on crée les zones avant les programmes, de sorte que l'on se retrouve avec des zones sans programme associé.

```
TypeError: /home/domopi/opt/remora_programmer/views/index.ejs:44
    42|     <p> <%= today %> </p>
    43|     <div>    
 >> 44|     <%
    45| for(var i=0; i<zones.length; i++) {
    46|     var program_semaine=zones[i].program;
    47|     for(var j=0; j<programs.length; j++) {

Cannot read property 'prog_5' of null
    at eval (eval at compile (/home/domopi/opt/remora_programmer/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:59:33)
    at returnedFn (/home/domopi/opt/remora_programmer/node_modules/ejs/lib/ejs.js:653:17)
    at tryHandleCache (/home/domopi/opt/remora_programmer/node_modules/ejs/lib/ejs.js:251:36)
    at View.exports.renderFile [as engine] (/home/domopi/opt/remora_programmer/node_modules/ejs/lib/ejs.js:482:10)
    at View.render (/home/domopi/opt/remora_programmer/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/domopi/opt/remora_programmer/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/domopi/opt/remora_programmer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/domopi/opt/remora_programmer/node_modules/express/lib/response.js:1008:7)
    at Statement.db.all (/home/domopi/opt/remora_programmer/server.js:94:7)
    at Statement.replacement (/home/domopi/opt/remora_programmer/node_modules/sqlite3/lib/trace.js:19:31)
```

**Comment by trahay** [comment]
Merci pour le bug report.
Ca devrait être corrigé maintenant.
